spring:
  application:
    name: mod-ext-events

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true

  kafka:
    consumer:
      group-id: externalized-demo
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.apache.kafka.common.config.AbstractConfig: WARN
    org.apache.kafka.common.utils.AppInfoParser: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
